
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello
    username: admin
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect